//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHRMSApi.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorCommercialTaxDepartment
    {
        public int ID { get; set; }
        public string ProfessionalTaxRegistrationNo_DateOfIssue { get; set; }
        public byte[] ProfessionalTaxRegistrationNo_DateOfIssueSoftCopy { get; set; }
        public string WebsiteOfCTDDepartment { get; set; }
        public string WebsiteOfCTDDepartmentID { get; set; }
        public string WebsiteOfCTDDepartmentPassword { get; set; }
        public int ContractorId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    
        public virtual ContractorMaster ContractorMaster { get; set; }
    }
}
