//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHRMSApi.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorShopAndEstablishmentDepartment
    {
        public int ID { get; set; }
        public string Shop_EstablishmentRegistrationNo_DateOfIssue { get; set; }
        public byte[] Shop_EstablishmentRegistrationNo_DateOfIssueSoftCopy { get; set; }
        public Nullable<System.DateTime> DurationOfShop_EstablishmentLicenceFromDate { get; set; }
        public Nullable<System.DateTime> DurationOfShop_EstablishmentLicenceToDate { get; set; }
        public Nullable<System.DateTime> DurationOfShop_EstablishmentLicenceLastRenewDate { get; set; }
        public string RegisteredTradeUnderShop_EstablishmentLicence { get; set; }
        public byte[] UdhyogAadhaarRegistrationNo_DateOfIssue { get; set; }
        public byte[] UdhyogAadhaarRegistrationNo_DateOfIssueSoftCopy { get; set; }
        public string UAN { get; set; }
        public string RegisteredTradeUnderUdhyogAadhaarLicence { get; set; }
        public string WebsiteOfUdhyogAadhaarDepartment { get; set; }
        public string WebsiteOfUdhyogAadhaarDepartmentID { get; set; }
        public string WebsiteOfUdhyogAadhaarDepartmentPassword { get; set; }
        public int ContactorId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    
        public virtual ContractorMaster ContractorMaster { get; set; }
    }
}
