//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHRMSApi.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorLabourAndEmploymentDepartment
    {
        public int ID { get; set; }
        public string Name_AddressUnderWhichContractIsCarriedOn { get; set; }
        public string Name_AddressOfPrincipleEmployer { get; set; }
        public byte[] ContractLabourLicenseNo_DateOfIssue { get; set; }
        public Nullable<System.DateTime> DurationOfLicenseFromDate { get; set; }
        public Nullable<System.DateTime> DurationOfLicenseToDate { get; set; }
        public Nullable<System.DateTime> DurationOfLicenseRenewDate { get; set; }
        public string Nature_LocationOfWork { get; set; }
        public string MaximumLabourAllowedAnyWorkingDay { get; set; }
        public int ContractorId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    
        public virtual ContractorMaster ContractorMaster { get; set; }
    }
}
