//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHRMSApi.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompanyMaster
    {
        public int CompanyId { get; set; }
        public int AppointmentTypeID { get; set; }
        public int EmployeeId { get; set; }
        public bool OverTimeApplicability { get; set; }
        public int ContractorId { get; set; }
        public string EmployeeIdCode { get; set; }
        public int ID { get; set; }
        public int DesignationId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        public virtual AppointmentTypeMaster AppointmentTypeMaster { get; set; }
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual ContractorMaster ContractorMaster { get; set; }
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual GradeMaster GradeMaster { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
        public virtual EmployeePersonalDetails EmployeePersonalDetails { get; set; }
    }
}
