//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHRMSApi.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompanyMaster
    {
        public int CompanyId { get; set; }
        public string AppointmentType { get; set; }
        public string Designation { get; set; }
        public string Category { get; set; }
        public string Grade { get; set; }
        public string Department { get; set; }
        public string Plant { get; set; }
        public int EmployeeId { get; set; }
        public bool OverTimeApplicability { get; set; }
        public int ContractorId { get; set; }
        public string EmployeeIdCode { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual ContractorMaster ContractorMaster { get; set; }
        public virtual EmployeePersonalDetails EmployeePersonalDetails { get; set; }
    }
}
