//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHRMSApi.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContractorMaster
    {
        public int ContractorId { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public System.DateTime DateOfResignation { get; set; }
        public System.DateTime DateOfLeaving { get; set; }
        public System.DateTime DateOfTermination { get; set; }
        public System.DateTime DateOfRetirement { get; set; }
        public System.DateTime DateOfConfirmation { get; set; }
        public string ReasonForLeaving { get; set; }
        public string ReasonForTermination { get; set; }
        public int EmployeeId { get; set; }
        public int ModeOfPaymentId { get; set; }
        public string SavingBankAccountNumber { get; set; }
        public string NameOfBank { get; set; }
        public string BankAddress { get; set; }
        public string BranchOfBank { get; set; }
        public string IFSCNumber { get; set; }
        public string MICRNumber { get; set; }
        public bool ProfessionalTaxApplicability { get; set; }
        public bool GujaratLabourWelfareFundApplicability { get; set; }
        public bool ProvidentfundApplicability { get; set; }
        public string UniversalAccountNumber { get; set; }
        public string PFAccountNumber { get; set; }
        public bool EmployeeStateInsuranceCorporationApplicability { get; set; }
        public string ESICIPNumber { get; set; }
    
        public virtual ContractorMaster ContractorMaster { get; set; }
        public virtual EmployeePersonalDetails EmployeePersonalDetails { get; set; }
        public virtual ModeOfPaymentMaster ModeOfPaymentMaster { get; set; }
    }
}
