//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalHRMSApi.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePersonalDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeePersonalDetails()
        {
            this.EmployeeNominationMaster = new HashSet<EmployeeNominationMaster>();
            this.EmployeeDocumentMaster = new HashSet<EmployeeDocumentMaster>();
            this.EmployeeContractorMaster = new HashSet<EmployeeContractorMaster>();
            this.EmployeeCompanyMaster = new HashSet<EmployeeCompanyMaster>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int MaritalStatusId { get; set; }
        public System.DateTime DateOfMarriage { get; set; }
        public int Age { get; set; }
        public int ReligionId { get; set; }
        public int GenderId { get; set; }
        public int BloodGroupId { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Education { get; set; }
        public string MobileNo { get; set; }
        public string EmergencyContactNo { get; set; }
        public string EmailId { get; set; }
        public string PermenantAddressLine1 { get; set; }
        public string PermenantAddressLine2 { get; set; }
        public string TemporaryAddressLine1 { get; set; }
        public string TemporaryAddressLine2 { get; set; }
        public int PermenantAddressCountryId { get; set; }
        public int PermenantAddressStateId { get; set; }
        public int PermenantAddressCityId { get; set; }
        public int TemporaryAddressCountryId { get; set; }
        public int TemporaryAddressStateId { get; set; }
        public int TemporaryAddressCityId { get; set; }
    
        public virtual BloodGroupMaster BloodGroupMaster { get; set; }
        public virtual GenderMaster GenderMaster { get; set; }
        public virtual MaritalStatusMaster MaritalStatusMaster { get; set; }
        public virtual ReligionMaster ReligionMaster { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual CityMaster CityMaster1 { get; set; }
        public virtual CountyMaster CountyMaster { get; set; }
        public virtual CountyMaster CountyMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeNominationMaster> EmployeeNominationMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual StateMaster StateMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDocumentMaster> EmployeeDocumentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContractorMaster> EmployeeContractorMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCompanyMaster> EmployeeCompanyMaster { get; set; }
    }
}
